apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: powerdns-admin
    app.kubernetes.io/part-of: powerdns
    app.kubernetes.io/component: admin
  name: powerdns-admin
  namespace: powerdns
spec:
  replicas: 1
  selector:
   matchLabels:
    app.kubernetes.io/name: powerdns-admin
    app.kubernetes.io/part-of: powerdns
    app.kubernetes.io/component: admin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: powerdns-admin
        app.kubernetes.io/part-of: powerdns
        app.kubernetes.io/component: admin
    spec:
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "pdns-admin"
      containers:
      - name: pdns-admin
        image: pschiffe/pdns-admin
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: PDNS_ADMIN_SQLA_DB_TYPE
          value: postgres
        - name: PDNS_ADMIN_SQLA_DB_HOST
          value: "powerdns-postgres-rw"
        - name: PDNS_ADMIN_SQLA_DB_PORT
          value: "5432"
        - name: PDNS_ADMIN_SQLA_DB_USER
          value: "pdnsadmin"
        - name: PDNS_ADMIN_SQLA_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pdnsadmin-pg-secret
              key: password
        - name: PDNS_ADMIN_SQLA_DB_NAME
          value: "pdnsadmin"
        - name: PDNS_API_URL
          value: "http://pdns-primary-api:8081/"
        - name: PDNS_VERSION
          value: "4.9"
        - name: PDNS_API_KEY
          valueFrom:
            secretKeyRef:
              name: pdns-secret
              key: apiKey
        volumeMounts:
          - name: uploads
            mountPath: /opt/powerdns-admin/upload/
        resources:
          limits:
            cpu: 300m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 64Mi
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: powerdns-admin-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: powerdns-admin-pvc
    app.kubernetes.io/part-of: powerdns
    app.kubernetes.io/component: admin
  name: powerdns-admin-pvc
  namespace: powerdns
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: powerdns-admin-svc
    app.kubernetes.io/part-of: powerdns
    app.kubernetes.io/component: admin
  name: admin-dashboard-powerdns
  namespace: powerdns
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app.kubernetes.io/name: powerdns-admin
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: powerdns-admin-ingress
  namespace: powerdns
  labels:
    app.kubernetes.io/name: powerdns-admin-ingress
    app.kubernetes.io/part-of: powerdns
    app.kubernetes.io/component: admin-ingress
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
  - host: pdnsadmin.int.prossertech.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: admin-dashboard-powerdns
            port: 
              number: 80