apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  labels:
    release: kube-prometheus-stack
  name: docker 
  namespace: prometheus-stack
spec:
  staticConfigs:
  - labels:
      job: docker
    targets: 
    - 10.1.20.10:9323