apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  sources:
  - repoURL: https://charts.external-secrets.io
    targetRevision: 0.11.0
    chart: external-secrets
  - repoURL: https://github.com/drewjprosser/argo-internal.git
    path: infra/external-secrets
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-secrets
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: ''
    kind: ExternalSecret
    jsonPointers:
    - /spec/data