apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-subdir-external-provisioner
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
    targetRevision: 4.0.18
    chart: nfs-subdir-external-provisioner
    helm:
      releaseName: nfs-subdir-external-provisioner
      parameters:
        - name: nfs.server
          value: nfs-01.int.prossertech.com
        - name: nfs.path
          value: /data/rke/external
        - name: storageClass.defaultClass
          value: "true"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true