apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openldap
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  sources:
  - repoURL: https://github.com/drewjprosser/argo-internal.git
    targetRevision: HEAD
    path: infra/openldap
  - repoURL: https://jp-gouin.github.io/helm-openldap/
    targetRevision: 4.3.1
    chart: openldap-stack-ha
    helm:
      releaseName: openldap-stack-ha
      valuesObject:
        global:
          ldapDomain: prossertech.com
          existingSecret: openldap-secret
        ltb-passwd:
          enabled: false
        phpldapadmin:
          ingress:
            hosts:
            - ldapadmin-internal.int.prossertech.com
        persistence:
          storageClass: openebs-hostpath
        customLdifFiles:
          00-root.ldif: |
            # Root Creation
            dn: dc=prossertech,dc=com 
            objectClass: dcObject
            objectClass: organization
            o: Prossertech
          01-users.ldif: |
            dn: ou=users,dc=prossertech,dc=com 
            objectClass: organizationalUnit
            ou: users 
          02-groups.ldif: |
            dn: ou=groups,dc=prossertech,dc=com 
            objectClass: organizationalUnit
            ou: groups
  destination:
    server: "https://kubernetes.default.svc"
    namespace: openldap
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true