apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openldap
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  sources:
  - repoURL: https://github.com/drewjprosser/argo-internal.git
    targetRevision: HEAD
    path: infra/openldap
  - repoURL: https://jp-gouin.github.io/helm-openldap/
    targetRevision: 4.3.1
    chart: openldap-stack-ha
    helm:
      releaseName: openldap-stack-ha
      valuesObject:
        global:
          ldapDomain: prossertech.com
          existingSecret: openldap-secret
        ltb-passwd:
          enabled: false
        phpldapadmin:
          ingress:
            hosts:
            - ldapadmin-internal.int.prossertech.com
            tls:
            - secretName: int-prossertech-com
              hosts:
              - "*.int.prossertech.com"
        persistence:
          storageClass: openebs-hostpath
  destination:
    server: "https://kubernetes.default.svc"
    namespace: openldap
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true