apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: powerdns
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/drewjprosser/argo-internal.git
    targetRevision: HEAD
    path: infra/powerdns
  destination:
    server: "https://kubernetes.default.svc"
    namespace: powerdns
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true