apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://github.com/drewjprosser/argo-internal.git
    path: infra/prometheus-stack
    targetRevision: HEAD 
  - chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 66.3.1
    helm:
      releaseName: kube-prometheus-stack
      valuesObject: 
        ingress:
          enabled: "true"
          hosts:
          - grafana.int.prossertech.com
          - prometheus.int.prossertech.com
          - alertmanager.int.prossertech.com
          paths:
          - /
          tls: 
          - secretName: int-prossertech-com
            hosts:
            - grafana.int.prossertech.com
            - prometheus.int.prossertech.com
            - alertmanager.int.prossertech.com
  destination:
    server: "https://kubernetes.default.svc"
    namespace: prometheus-stack
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true