apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-s3
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://yandex-cloud.github.io/k8s-csi-s3/charts
    targetRevision: 0.42.1
    chart: csi-s3
    helm:
      releaseName: csi-s3
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    automated:
      prune: true
      selfHeal: true