apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  refreshInterval: 1d
  target:
    name: cloudflare-api-token-secret
    template:
      engineVersion: v2
      data:
        api-token: "{{ .apiToken }}"

  data:
  - secretKey: apiToken
    remoteRef:
      key: /cloudflare/cert-manager
      property: api-token

    