---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: pushsecret-tls 
  namespace: cert-manager
spec:
  updatePolicy: Replace 
  deletionPolicy: None 
  refreshInterval: 3m
  secretStoreRefs: 
    - name: vault-backend 
      kind: ClusterSecretStore
  selector:
    secret:
      name: int-prossertech-comNew

  data:
    - match:
        secretKey: tls.crt
        remoteRef:
          remoteKey: /tls/int.prossertech.com
          property: tls.crt
    - match:
        secretKey: tls.key
        remoteRef:
          remoteKey: /tls/int.prossertech.com
          property: tls.key
