apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: int-prossertech-com-vault
  namespace: vault
spec:
  secretName: int-prossertech-com-vault
  commonName: "*.int.prossertech.com"
  dnsNames:
  - int.prossertech.com 
  - "*.int.prossertech.com"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer