apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: int-prossertech-com
  namespace: vault
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  refreshInterval: 3m
  target:
    name: int-prossertech-com
    template:
      engineVersion: v2
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ .crt }}"
        tls.key: "{{ .key }}"
  data:
  - secretKey: crt
    remoteRef:
      key: /tls/int.prossertech.comNew
      property: tls.crt
  - secretKey: key
    remoteRef:
      key: /tls/int.prossertech.comNew
      property: tls.key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: int-prossertech-com
  namespace: vaultwarden
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  refreshInterval: 3m
  target:
    name: int-prossertech-com
    template:
      engineVersion: v2
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ .crt }}"
        tls.key: "{{ .key }}"
  data:
  - secretKey: crt
    remoteRef:
      key: /tls/int.prossertech.comNew
      property: tls.crt
  - secretKey: key
    remoteRef:
      key: /tls/int.prossertech.comNew
      property: tls.key