apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: altantis-secrets
  namespace: atlantis
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  refreshInterval: 3m
  target:
    name: atlantis-secrets
    template:
      engineVersion: v2
      data:
        webauth-username: "{{ .webauth_username }}"
        webauth-password: "{{ .webauth_password }}"
        github-token: "{{ .github_token }}"
        github-webhook-secret: "{{ .github_webhook_secret }}"
        vault-address: "{{ .vault_address }}"
        vault-username: "{{ .vault_username }}"
        vault-password: "{{ .vault_password }}"
        minio-access-key: "{{ .minio_access_key }}"
        minio-access-secret: "{{ .minio_access_secret }}"
  data:
    ## WebAuth ##
  - secretKey: webauth_username
    remoteRef:
      key: /atlantis-webauth
      property: username
  - secretKey: webauth_password
    remoteRef:
      key: /atlantis-webauth
      property: password

    ## Github ##
  - secretKey: github_token
    remoteRef:
      key: /github/token
      property: token
  - secretKey: github_webhook_secret
    remoteRef:
      key: /github/webhook
      property: secret

    ## Vault ##
  - secretKey: vault_address
    remoteRef:
      key: /vault
      property: address
  - secretKey: vault_username
    remoteRef:
      key: /vault
      property: username
  - secretKey: vault_password
    remoteRef:
      key: /vault
      property: password

    ## Minio ##
  - secretKey: minio_access_key
    remoteRef:
      key: /minio/minio-01
      property: ACCESS_KEY_ID
  - secretKey: minio_access_secret
    remoteRef:
      key: /minio/minio-01
      property: ACCESS_KEY_SECRET