apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: altantis-secrets
  namespace: atlantis
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  refreshInterval: 3m
  target:
    name: atlantis-secrets
    template:
      engineVersion: v2
      type: kubernetes.io/tls
      data:
        webauth-username: "{{ .webauth-username }}"
        webauth-password: "{{ .webauth-password }}"
        github-token: "{{ .github-token }}"
        github-webhook-secret: "{{ .github-webhook-secret }}"
        vault-address: "{{ .vault-address }}"
        vault-username: "{{ .vault-username }}"
        vault-password: "{{ .vault-password }}"
        minio-access-key: "{{ .minio-access-key }}"
        minio-access-secret: "{{ .minio-access-secret }}"
  data:
    ## WebAuth ##
  - secretKey: webauth-username
    remoteRef:
      key: /atlantis-webauth
      property: username
  - secretKey: webauth-password
    remoteRef:
      key: /atlantis-webauth
      property: password

    ## Github ##
  - secretKey: github-token
    remoteRef:
      key: /github/token
      property: token
  - secretKey: github-webhook-secret
    remoteRef:
      key: /github/webhook
      property: secret

    ## Vault ##
  - secretKey: vault-address
    remoteRef:
      key: /vault
      property: address
  - secretKey: vault-username
    remoteRef:
      key: /vault
      property: username
  - secretKey: vault-password
    remoteRef:
      key: /vault
      property: password

    ## Minio ##
  - secretKey: minio-access-key
    remoteRef:
      key: /minio/minio-01
      property: ACCESS_KEY_ID
  - secretKey: minio-access-secret
    remoteRef:
      key: /minio/minio-01
      property: ACCESS_KEY_SECRET