apiVersion: external_secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: altantis_secrets
  namespace: atlantis
spec:
  secretStoreRef:
    name: vault_backend
    kind: ClusterSecretStore
  refreshInterval: 3m
  target:
    name: atlantis_secrets
    template:
      engineVersion: v2
      type: kubernetes.io/tls
      data:
        webauth_username: "{{ .webauth_username }}"
        webauth_password: "{{ .webauth_password }}"
        github_token: "{{ .github_token }}"
        github_webhook_secret: "{{ .github_webhook_secret }}"
        vault_address: "{{ .vault_address }}"
        vault_username: "{{ .vault_username }}"
        vault_password: "{{ .vault_password }}"
        minio_access_key: "{{ .minio_access_key }}"
        minio_access_secret: "{{ .minio_access_secret }}"
  data:
    ## WebAuth ##
  - secretKey: webauth_username
    remoteRef:
      key: /atlantis_webauth
      property: username
  - secretKey: webauth_password
    remoteRef:
      key: /atlantis_webauth
      property: password

    ## Github ##
  - secretKey: github_token
    remoteRef:
      key: /github/token
      property: token
  - secretKey: github_webhook_secret
    remoteRef:
      key: /github/webhook
      property: secret

    ## Vault ##
  - secretKey: vault_address
    remoteRef:
      key: /vault
      property: address
  - secretKey: vault_username
    remoteRef:
      key: /vault
      property: username
  - secretKey: vault_password
    remoteRef:
      key: /vault
      property: password

    ## Minio ##
  - secretKey: minio_access_key
    remoteRef:
      key: /minio/minio_01
      property: ACCESS_KEY_ID
  - secretKey: minio_access_secret
    remoteRef:
      key: /minio/minio_01
      property: ACCESS_KEY_SECRET