apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: atlantis
  namespace: atlantis
spec:
  serviceName: atlantis
  replicas: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: atlantis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: atlantis
    spec:
      securityContext:
        fsGroup: 1000 # Atlantis group (1000) read/write access to volumes.
      containers:
      - name: atlantis
        image: ghcr.io/runatlantis/atlantis:v0.28.3 # 1. Replace <VERSION> with the most recent release.
        env:
        - name: ATLANTIS_ATLANTIS_URL
          value: https://atlantis.prossertech.com 
        - name: ATLANTIS_REPO_ALLOWLIST
          value: github.com/drewjprosser/* # 2. Replace this with your own repo allowlist.

          ### Web Auth ###
        - name: ATLANTIS_WEB_BASIC_AUTH
          value: "true" 
        - name: ATLANTIS_WEB_USERNAME
          valueFrom:
            secretKeyRef:
              name: atlantis-secrets 
              key: webauth-username
        - name: ATLANTIS_WEB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: atlantis-secrets
              key: webauth-password

        ### GitHub Config ###
        - name: ATLANTIS_GH_USER
          value: drewjprosser # 3i. If you're using GitHub replace <YOUR_GITHUB_USER> with the username of your Atlantis GitHub user without the `@`.
        - name: ATLANTIS_GH_TOKEN
          valueFrom:
            secretKeyRef:
              name: atlantis-secrets
              key: github-token
        - name: ATLANTIS_GH_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: atlantis-secrets
              key: github-webhook-secret
        ### End GitHub Config ###

        - name: ATLANTIS_DATA_DIR
          value: /atlantis
        - name: ATLANTIS_PORT
          value: "4141" # Kubernetes sets an ATLANTIS_PORT variable so we need to override.

          ## Configure Hashi Vault Env ##
        - name: VAULT_ADDR
          valueFrom:
            secretKeyRef:
              name: atlantis-secrets
              key: vault-address
        - name: TERRAFORM_VAULT_USERNAME
          valueFrom:
            secretKeyRef:
              name: atlantis-secrets
              key: vault-username
        - name: TERRAFORM_VAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: atlantis-secrets
              key: vault-password

          ## Configure Minio Backend ##
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: atlantis-secrets
              key: minio-access-key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: atlantis-secrets
              key: minio-access-secret

        volumeMounts:
        - name: atlantis-data
          mountPath: /atlantis
        - name: atlantis-terraform
          mountPath: /terraform
        ports:
        - name: atlantis
          containerPort: 4141
        resources:
          requests:
            memory: 1Gi
            cpu: 600m
          limits:
            memory: 1Gi
            cpu: 600m
        livenessProbe:
          # We only need to check every 60s since Atlantis is not a
          # high-throughput service.
          periodSeconds: 60
          httpGet:
            path: /healthz
            port: 4141
            # If using https, change this to HTTPS
            scheme: HTTP
        readinessProbe:
          periodSeconds: 60
          httpGet:
            path: /healthz
            port: 4141
            # If using https, change this to HTTPS
            scheme: HTTP
  volumes: 
    - name: atlantis-terraform
      persistentVolumeClaim: 
        claimName: csi-s3-manual-pvc
  volumeClaimTemplates:
  - metadata:
      name: atlantis-data
    spec:
      accessModes: ["ReadWriteOnce"] # Volume should not be shared by multiple nodes.
      resources:
        requests:
          # The biggest thing Atlantis stores is the Git repo when it checks it out.
          # It deletes the repo after the pull request is merged.
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: atlantis
  namespace: atlantis
spec:
  type: ClusterIP
  ports:
  - name: atlantis
    port: 80
    targetPort: 4141
  selector:
    app.kubernetes.io/name: atlantis
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: atlantis
  namespace: atlantis
  labels:
    name: atlantis
spec:
  ingressClassName: nginx
  rules:
  - host: atlantis-internal.int.prossertech.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: atlantis
            port: 
              name: atlantis
