apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  service_type: clusterip
  ingress_type: ingress 
  ingress_hosts: 
    - hostname: awx-internal.int.prossertech.com
  ingress_controller: nginx