apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared-credentials
  namespace: cloudflared
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  refreshInterval: 3m
  target:
    name: cloudflared-credentials
    template:
      engineVersion: v2
      data:
        credentials.json: "{{ .credentials }}"
  data:
  - secretKey: credentials
    remoteRef:
      key: /cloudflared/internal
      property: credentials

    