---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgAPc0c0DJfCWyzakWFHQfpDuGSGGnP6Dv+EeBRFQvbWj/ei6dQ8TBOiPeWX0x3OlWKxeAWDs32S8CMSjQStV0wkbJDq4+aB1aGQQXbwvY2xNzOC9cn+b0a67I73kaakbK5YsHhFn5fezQG2/ZOUDSppk6CM5nw2pz6yCLTcCSztCJHR6X5tZJ4RTYblpjo2PoVYFWnbeSDCpCzX1JRtqybSQpY4Hp2kRCWS+/32LYZNcQK+X99Rljg6RusI/bku6Ny/vXSKcOjBNmQcxga/eW0eh7ZLU6eoTHrCzEba5IQVUuTYlpG0rAOfi7WjAD2+mVM5dCtcwv9imgisAFrhpoPHrd4QcR71Fz6xAADBlSssP31vbM9G3Nsj6QHkDdLJWtIxThkjbdgMaQaCiuBcTwZtqUS/ta6cRHd4TszSloeWnG6IgpCf7R/yv6R9DEYQaYCRVTMAq0sANOpYK2kbSn2j/C8IzTJFg7nWvGKwrHnuWDeBOY8LvFnfxslaU5SHwXquD5tXqxCNINCU43ugJtbsmxo6S+l4hc30ZAxG+oTiyNWduwDgf8Gl8nLOQK+O1Ru2+ttFbQUDYMtX3DSxOOoiB7AZKK6cWQ6PK8N8PFZQ/8P0Cr6q7RHf54u4lYS7kO6xKoVl3L0J9PF7q3DTi2/QMR4UVibJGaNf/cEt9S6VF9REOgNAOrN9yGf2yFCq5BzAWT+O0651hvKIkisr0vMuDvQLjQbe4/KU98amDFPwVKt+6rdQ5SHp1ZtdE0TITlSJqkX4hKWLmo/OwwTnpKhmJ45QdpB9XkrwAK9fWRPHVFBg8x72zPuccsi52YikbJ/I1aR+Ub/3JKYHqGYEiW/ga7V5fgAJm38GH+C1RnihhsuYNwbFDCc0b7zJNr448e8AG2y3vTlDm9jJeEqymxlUPA==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflared
