apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: csi-s3-secret
  namespace: kube-system
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  refreshInterval: 3m
  target:
    name: csi-s3-secret
    template:
      engineVersion: v2
      data:
        accessKeyID: "{{ .accessKeyID }}"
        secretAccessKey: "{{ .secretAccessKey }}"
        endpoint: "{{ .endpoint }}"
  data:
  - secretKey: accessKeyID
    remoteRef:
      key: /minio/minio-01
      property: ACCESS_KEY_ID
  - secretKey: secretAccessKey 
    remoteRef:
      key: /minio/minio-01
      property: ACCESS_KEY_SECRET
  - secretKey: endpoint
    remoteRef:
      key: /minio/minio-01
      property: endpoint
    