apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openldap-secret
  namespace: openldap
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  refreshInterval: 3m
  target:
    name: openldap-secret
    template:
      engineVersion: v2
      data:
        LDAP_ADMIN_PASSWORD: "{{ .password }}"
        LDAP_CONFIG_ADMIN_PASSWORD: "{{ .password }}"
  data:
  - secretKey: password
    remoteRef: 
      key: /ldap
      property: password
    