apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openldap-secret
  namespace: openldap
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  refreshInterval: 3m
  target:
    name: openldap-secret
    template:
      engineVersion: v2
      stringData:
        LDAP_ADMIN_USERNAME: "{{ .username }}"
        LDAP_ADMIN_PASSWORD: "{{ .password }}"
        LDAP_CONFIG_ADMIN_USERNAME: "{{ .username }}"
        LDAP_CONFIG_ADMIN_PASSWORD: "{{ .password }}"
        LDAP_CONFIG_ADMIN_ENABLED: "{{ .enabled }}"
        LDAP_ROOT: "{{ .root }}"
  dataFrom:
  - secretKey: username
    remoteRef: 
      key: /ldap
      property: username
  - secretKey: password
    remoteRef: 
      key: /ldap
      property: password
  - secretKey: enabled
    remoteRef: 
      key: /ldap
      property: enabled
  - secretKey: root
    remoteRef: 
      key: /ldap
      property: root
    